### ISSUE TITLE
Dispose of the TextEditingController

### ISSUE THREAD

**Issue by dmakwt** [devq8/wasfat_frontend#15]
https://github.com/devq8/wasfat_frontend/blob/2e555fd1a4ee0a593fa06b1a82d0ef00e33712d3/wasfat_frontend/lib/pages/auth/signin.dart#L9-L10

**Good Practice:**
Remember to dispose of the TextEditingController when it is no longer needed. So every time when you create a new TextEditingController object, dispose it inside "dispose" method.

To dispose **usernameController**  & **passwordController**  , add this line. 
```dart
  @override
  void dispose() {
    usernameController.dispose();
    passwordController.dispose();
    super.dispose();
  }
```

**Comment by devq8** [comment]
This is done, but my question is this applied only for TextEditingController ? or any variable ?

**Comment by dmakwt** [comment]
> This is done, but my question is this applied only for TextEditingController ? or any variable ?

Yes, it's applied just for the Controllers such as **TextEditingController**, **PageController**, and other controllers. For more details, check the documentation. 
https://api.flutter.dev/flutter/widgets/TextEditingController-class.html
