### ISSUE TITLE
Source files using lowercase_with_underscores

### ISSUE THREAD

**Issue by dmakwt** [devq8/wasfat_frontend#16]
Follow this style, when you create a new dart file.
https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores

❌
> wasfat_frontend/lib/pages/auth/**signin.dart**
> wasfat_frontend/lib/pages/auth/**signup.dart**

✔
> wasfat_frontend/lib/pages/auth/**sign_in.dart**
> wasfat_frontend/lib/pages/auth/**sign_up.dart**

**Comment by devq8** [comment]
Great, changed.
