### ISSUE TITLE
Type await keyword

### ISSUE THREAD

**Issue by dmakwt** [devq8/wasfat_frontend#17]
Don't forget to add **await** keyword before **loadCategories** & **loadIngredients** methods. It's very important to use await keyword inside **onRefresh** method

https://github.com/devq8/wasfat_frontend/blob/2e555fd1a4ee0a593fa06b1a82d0ef00e33712d3/wasfat_frontend/lib/pages/category/categories.dart#L29

https://github.com/devq8/wasfat_frontend/blob/2e555fd1a4ee0a593fa06b1a82d0ef00e33712d3/wasfat_frontend/lib/pages/ingredient/ingredients.dart#L46

**Comment by devq8** [comment]
Done
