### ISSUE TITLE
Create Drawer StatelessWidget

### ISSUE THREAD

**Issue by dmakwt** [devq8/wasfat_frontend#18]
**Good Practice:**
For better clean code, create a new StatelessWidget, and add the drawer inside it.

https://github.com/devq8/wasfat_frontend/blob/2e555fd1a4ee0a593fa06b1a82d0ef00e33712d3/wasfat_frontend/lib/pages/recipe/list.dart#L28-L92

**Comment by devq8** [comment]
Done
